### PR TITLE
Added account details to account details page

### PR DESCRIPTION
**Pull request by rcefalu10**
Still needs some style work and new password is being weird but figured I would get this merged in so others can build on this
Screen Shot 2020-09-02 at 12 09 58 PM

### CODE REVIEW

**Comment by danielgsmith** [comment]
not sure if we need reset my password and new password? kinda redundant... would lean towards just new password an reserve reset with email for only the login page (reset via email also only works for accounts based on email - not google, so this could be confusing and not work if using google for login)

**Comment by rcefalu10** [comment]
Screen Shot 2020-09-02 at 2 02 46 PM

@danielgsmith

**Comment by rcefalu10** [comment]
Doesnt look great but swithced everything over to Material UI and is functional for now

**Review by danielgsmith — COMMENTED** [review]
good enough for now

**Review by danielgsmith — APPROVED** [review]

**Pull request merged**
